url: 'https://captainmeehan.github.io/'
baseurl: "/studious-funicular"
theme: jekyll-theme-midnight
title: Portfolio for Fredrik Andersson in Game Programming
author: Fredrik Andersson
description: “I am part of The Game Assembly’s internship program. As per the agreement between the Games Industry and The Game Assembly, neither student nor company may be in contact with one another regarding internships before April 23rd. Any internship offers can be made on May 5th, at the earliest.”
